In [1]:
import pandas as pd
import numpy as np
from re import sub

df = pd.read_csv('../data/dataset.csv', encoding='latin1')

In [2]:
df = df.iloc[:, 1:].copy()
df = df.dropna()

In [3]:
df['City'] = df['City'].str.capitalize()
df['Cuisine Style'] = df['Cuisine Style'].str.lower()
df['keyword'] = df['keyword'].str.lower()
df['keyword'] = df['keyword'].str.strip()

df['Cuisine Style'] = df['Cuisine Style'].apply(lambda x: ' '.join(x.split(',')).split())
df['keyword'] = df['keyword'].apply(lambda x: sub(' +', ' ', x))

df = df.sort_values(['Ranking', 'Rating'], ascending=[True, False])

In [4]:
df = df.sample(5000)
df.sample(10)

,Name,City,Cuisine Style,Ranking,Rating,Price Range,keyword
32907,Focacceria,Oslo,[italian],665.0,4.5,cheap,oslo cheap
47426,L'Estanquet,Lyon,[french],366.0,4.5,casual,lyon casual westerneuropean
48961,La Castellana,Berlin,[italian],3014.0,4.0,casual,berlin casual
27301,Don Pepe Menyecske,Budapest,"[italian, pizza, mediterranean, european, inte...",15.0,5.0,casual,budapest casual vegetarian mediterranean inter...
100869,Trattoria Caprese,Milan,"[italian, pizza, seafood, mediterranean, veget...",644.0,4.0,casual,milan casual vegetarian mediterranean seafood ...
97954,The Lekkerbek,London,"[italian, cafe, british, fusion]",7916.0,4.5,cheap,london cheap cafe fusion westerneuropean
18517,Capriccio,Paris,[italian],4607.0,4.5,cheap,paris cheap
98815,The Sampler,London,[winebar],6776.0,4.0,casual,london casual
10910,Bistrotheque,London,"[european, british, vegetarianfriendly, gluten...",1222.0,4.0,casual,london casual vegetarian westerneuropean
65912,Mutte,Madrid,[asian],2623.0,4.0,casual,madrid casual asian

In [5]:
params = {'cuisine': 'any food', 'price': 'any price', 'city': 'anywhere'}

def find_restaurant(df, cuisine=params['cuisine'], price=params['price'], city=params['city'], num=5):
    condition = None
    multiple = False
    
    if (cuisine != params['cuisine']):
        condition = df['Cuisine Style'].str.contains(cuisine.lower(), regex=False)
        multiple = True
    
    if (price != params['price']):
        if multiple:
            condition = condition & (df['Price Range'] == price.lower())
        else:
            condition = df['Price Range'] == price.lower()
            multiple = True

    if (city != params['city']):
        if multiple:
            condition = condition & (df['City'].str.lower() == city.lower())
        else:
            condition = df['City'].str.lower() == city.lower()
    
    gl = df[condition].sort_values(['Ranking', 'Rating'], ascending=[True, False])
    
    return gl.head(num)

In [6]:
find_restaurant(df, city='Hamburg', price='casual', cuisine='german')

,Name,City,Cuisine Style,Ranking,Rating,Price Range,keyword
32460,Fischmarkt,Hamburg,"[german, seafood, european, soups]",56.0,4.5,casual,hamburg casual seafood soups westerneuropean
34803,Gasthaus Heimathafen,Hamburg,"[bar, german, seafood, european, gastropub, ce...",73.0,4.0,casual,hamburg casual bar vegetarian seafood centrale...
2843,Alte Muehle,Hamburg,[german],233.0,4.5,casual,hamburg casual westerneuropean
104992,Wasserschloss Speicherstadt,Hamburg,"[german, european, centraleuropean, vegetarian...",245.0,3.5,casual,hamburg casual vegetarian centraleuropean west...
12958,Brechtmanns Bistro,Hamburg,"[german, asian]",350.0,4.5,casual,hamburg casual westerneuropean asian